version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:21.1.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
    command: start-dev
    ports:
      - "8080:8080"

  spring-app:
    build: .
    container_name: spring-keycloak-demo
    ports:
      - "8081:8081"
    environment:
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=demo-realm
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/demo-realm
    depends_on:
      - keycloak
